name: Deploy to Server

on:
  push:
    branches: [ master ]  # Триггер — пуш в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Клонируем код
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Логинимся в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 3. Собираем и пушим образ
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ermakov880/myapp:latest

      # 4. Подключаемся по SSH к серверу и обновляем контейнер
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd Devops
            git pull
            docker stop myapp || true   # убиваем старый контейнер, если был запущен вручную
            docker rm myapp || true
            docker compose pull
            docker compose up -d --remove-orphans

      # 5. Устанавливаем Ansible на раннер
      - name: Install Ansible
        run: sudo apt update && sudo apt install ansible -y

      # 6. Настраиваем SSH-ключ для Ansible и запускаем плейбук
      - name: Setup SSH key and run Ansible
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          cd ansible
          ansible-playbook -i inventory.ini playbook.yml -v
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"